### ISSUE TITLE
Замечания от 21.05.2017

### ISSUE THREAD

**Issue by QuickNickKoenig** [thanator/animals#1]
Code convention:
- определись с ним. Пусть везде будет одинаковым.

AnimalClass:
- Почему AnimalClass, а не просто Animal?
- Нужен equals()/hashCode().

MainActivity:
- Code convention.
- animalAdapter без квалификатора.
- неиспользуемое поле TextView.
- AnimalStorageProvider AnimalsProvider = (AnimalStorageProvider) getApplication(); почему название переменной с большой буквы?
- private AnimalStorage mAnimalLoader; -- это всё-таки Storage, а не Loader.

AnimalAdding:
- У активити должен быть суффикс Activity в названии класса.
- Название переменных -- должно быть с маленькой буквы.
- private EditText[] mEditText; -- mEditTexts. Множественное число.

AnimalStorage:
- Вначале объявляются поля, потом конструктор.
- статические поля пишутся с префиксом s.
- Что название слушателя, что название метода в нём -- без camelCase-а.

AnimalLoader:
- private List<AnimalClass> firstStart; -- неудачное название.

**Comment by thanator** [comment]
Поправил все замечания + изменил слегка визуал элементов в ListView
